
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module digital_lock(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED (High Active) //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY (Active Low) //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 (Low Active) //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// SRAM //////////
	output		    [18:0]		SRAM_ADDR,
	inout 		    [15:0]		SRAM_DQ,
	output		          		SRAM_CE_N,
	output		          		SRAM_OE_N,
	output		          		SRAM_WE_N,
	output		          		SRAM_LB_N,
	output		          		SRAM_UB_N,

	//////////// Fan Control //////////
	inout 		          		FAN_CTRL
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

assign HEX3 = 7'h7F;
assign HEX4 = 7'h7F;
assign HEX5 = 7'h7F;
assign HEX6 = 7'h7F;
assign HEX7 = 7'h7F;

digital_safe_lock #(
	.DB_DELAY(20'd1_000_000),
	.TIMER_CYCLES(28'd100_000_000),
	.SRAM_WAIT_CYCLES(2)
) lock_core (
	.CLOCK_50(CLOCK_50),
	.SW(SW),
	.KEY(KEY),
	.LEDR(LEDR),
	.LEDG(LEDG),
	.HEX2(HEX2),
	.HEX1(HEX1),
	.HEX0(HEX0),
	.LCD_ON(LCD_ON),
	.LCD_RS(LCD_RS),
	.LCD_RW(LCD_RW),
	.LCD_EN(LCD_EN),
	.LCD_DATA(LCD_DATA),
	.SRAM_ADDR(SRAM_ADDR),
	.SRAM_DQ(SRAM_DQ),
	.SRAM_CE_N(SRAM_CE_N),
	.SRAM_OE_N(SRAM_OE_N),
	.SRAM_WE_N(SRAM_WE_N),
	.SRAM_LB_N(SRAM_LB_N),
	.SRAM_UB_N(SRAM_UB_N)
);


	//////////// FAN Control //////////
assign FAN_CTRL = 1'bz; // turn on FAN


endmodule
